version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ebschedule
    main: .
    binary: ebschedule
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}

archives:
  - id: ebschedule
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot+{{ .ShortCommit }}"

release:
  github:
    owner: rrreeeyyy
    name: ebschedule
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'Merge pull request'
